spring.application.name=DevslopsOrdersStockLine


#######
spring.datasource.url=jdbc:mysql://localhost:3306/stocklineorders
spring.datasource.username=root
spring.datasource.password=htl2025*F1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql: true
spring.datasource.driverClassName=com.mysql.jdbc.Driver
##################
#### Security
##################
security.jwt.secret=REVWU0xPUFNMRU9OLVNUT0NLTElORTIwMTYqNw==
security.jwt.access-minutes=60
security.jwt.refresh-days=14